version: '3.8'

services:
  # ===================
  # INFRASTRUCTURE SERVICES
  # ===================
  
  postgres-staging:
    image: postgres:16-alpine
    container_name: devsfit-postgres-staging
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: devsfit_staging
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres-staging-data:/var/lib/postgresql/data
    networks:
      - devsfit-staging-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d devsfit_staging"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    restart: unless-stopped

  redis-staging:
    image: redis:7-alpine
    container_name: devsfit-redis-staging
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-password}
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis-staging-data:/data
    networks:
      - devsfit-staging-network
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${REDIS_PASSWORD:-password}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped

  rabbitmq-staging:
    image: rabbitmq:3-management-alpine
    container_name: devsfit-rabbitmq-staging
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-password}
    volumes:
      - rabbitmq-staging-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - devsfit-staging-network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f rabbitmq"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped

  # ===================
  # MICROSERVICES (LOCAL BUILD)
  # ===================
  
  api-gateway-staging:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile.dev
    container_name: devsfit-api-gateway-staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - PORT=3000
      - REDIS_HOST=redis-staging
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-admin}:${RABBITMQ_PASSWORD:-password}@rabbitmq-staging:5672
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres-staging:5432/devsfit_staging
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - RATE_LIMIT_REDIS_HOST=redis-staging
      - PROMETHEUS_PORT=9090
    depends_on:
      postgres-staging:
        condition: service_healthy
      redis-staging:
        condition: service_healthy
    networks:
      - devsfit-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped

  auth-service-staging:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    container_name: devsfit-auth-service-staging
    ports:
      - "3020:3020"
    environment:
      - NODE_ENV=staging
      - PORT=3020
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres-staging:5432/devsfit_staging
      - REDIS_HOST=redis-staging
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-your-refresh-secret}
      - PROMETHEUS_PORT=9464
    depends_on:
      postgres-staging:
        condition: service_healthy
      redis-staging:
        condition: service_healthy
    networks:
      - devsfit-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3020/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped

  package-service-staging:
    build:
      context: ./services/package-service
      dockerfile: Dockerfile.dev
    container_name: devsfit-package-service-staging
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=staging
      - PORT=3003
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres-staging:5432/devsfit_staging
      - REDIS_HOST=redis-staging
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
      - PROMETHEUS_PORT=9466
    depends_on:
      postgres-staging:
        condition: service_healthy
      redis-staging:
        condition: service_healthy
    networks:
      - devsfit-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped

  billing-service-staging:
    build:
      context: ./services/billing-service
      dockerfile: Dockerfile.dev
    container_name: devsfit-billing-service-staging
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=staging
      - PORT=3004
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres-staging:5432/devsfit_staging
      - REDIS_HOST=redis-staging
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
      - PROMETHEUS_PORT=9467
    depends_on:
      postgres-staging:
        condition: service_healthy
      redis-staging:
        condition: service_healthy
    networks:
      - devsfit-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped

  payment-service-staging:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile.dev
    container_name: devsfit-payment-service-staging
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=staging
      - PORT=3005
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres-staging:5432/devsfit_staging
      - REDIS_HOST=redis-staging
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
      - SSLCOMMERZ_STORE_ID=${SSLCOMMERZ_STORE_ID:-testbox}
      - SSLCOMMERZ_STORE_PASSWORD=${SSLCOMMERZ_STORE_PASSWORD:-qwerty}
      - SSLCOMMERZ_SANDBOX=${SSLCOMMERZ_SANDBOX:-true}
      - PROMETHEUS_PORT=9468
    depends_on:
      postgres-staging:
        condition: service_healthy
      redis-staging:
        condition: service_healthy
    networks:
      - devsfit-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped

  # ===================
  # MONITORING (STAGING)
  # ===================
  
  prometheus-staging:
    image: prom/prometheus:latest
    container_name: devsfit-prometheus-staging
    ports:
      - "9091:9090"
    volumes:
      - ./infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-staging-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    networks:
      - devsfit-staging-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    restart: unless-stopped

  grafana-staging:
    image: grafana/grafana:latest
    container_name: devsfit-grafana-staging
    ports:
      - "3014:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
    volumes:
      - grafana-staging-data:/var/lib/grafana
      - ./infrastructure/monitoring/grafana-dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      - prometheus-staging
    networks:
      - devsfit-staging-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped

  jaeger-staging:
    image: jaegertracing/all-in-one:latest
    container_name: devsfit-jaeger-staging
    ports:
      - "16687:16686"
      - "14269:14268"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    networks:
      - devsfit-staging-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped

# ===================
# VOLUMES (STAGING)
# ===================

volumes:
  postgres-staging-data:
  redis-staging-data:
  rabbitmq-staging-data:
  prometheus-staging-data:
  grafana-staging-data:

# ===================
# NETWORKS (STAGING)
# ===================

networks:
  devsfit-staging-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
