apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: devsfit
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - name: http
    port: 3020
    targetPort: 3020
    protocol: TCP
  type: ClusterIP
